FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir poetry

COPY . .

RUN poetry config virtualenvs.create false && \
    poetry install --no-interaction --no-ansi

ARG NER_SERVICE_PORT
ENV NER_SERVICE_PORT=${NER_SERVICE_PORT}

EXPOSE ${NER_SERVICE_PORT}

CMD sh -c "poetry run uvicorn api.main:app --host 0.0.0.0 --reload --port ${NER_SERVICE_PORT}"
