FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir poetry

COPY . .

RUN poetry config virtualenvs.create false && \
    poetry install --no-interaction --no-ansi

ARG EMBEDDING_SERVICE_PORT
ENV EMBEDDING_SERVICE_PORT=${EMBEDDING_SERVICE_PORT}

EXPOSE ${EMBEDDING_SERVICE_PORT}

CMD sh -c "poetry run uvicorn api.main:app --host 0.0.0.0 --reload --port ${EMBEDDING_SERVICE_PORT}"
